name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} # Use the PAT for authentication

      - name: Print Current Working Directory
        run: pwd

      - name: List All Files in Directory
        run: ls -R

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Update Script
        run: python update_readme.py

      - name: Push Changes
        run: |
          git config --global user.name "Aloffawy"
          git config --global user.email "your_email@example.com"
          git add README.md
          git commit -m "Automated update"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/aloffawy/daily-alert.git HEAD:main
